document_root: "/www"

hooks:
    build: |
      drush make drupal.make www --prepare-install -y
      echo "\$databases['default']['default'] = array(
        'driver' => 'mysql',
        'database' => 'drupal',
        'username' => 'drupal',
        'password' => 'drupal',
        'host' => 'database',
      );" >> www/sites/default/settings.php
    enable_first: |
      drush {{alias}} site-install -y
      drush {{alias}} uli
    deploy: |
      drush {{alias}} updb -y
      drush {{alias}} cc all
